with-expecter: true
dir: mocks
outpkg: mocks
packages:
    github.com/razzzp/apdu-interpreter/interpreter:
        # place your package-specific config here
        config:
        interfaces:
            # select the interfaces you want mocked
            Interpretation:
                # Modify package-level config for this specific interface (if applicable)
                config: